---
id: tokyodebian-debexpo-20160625
base_name: tokyodebian-debexpo-20160625
tags: []
presentation_date: 
version: 2016.06.25
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kentaro Hayashi
  email: kenhys@gmail.com
  rubygems_user: kenhys
  slideshare_user: kenhys
  speaker_deck_user: 
