---
id: tokyodebian-debexpo-20160625
base_name: tokyodebian-debexpo-20160625
tags:
  - rabbit
  - debian
  - debexpo
presentation_date: 2016-06-25
version: 2016.06.25
licenses:
  - CC-BY-SA-4.0
slideshare_id: tokyodebian-debexpo-20160625
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kentaro Hayashi
  email: kenhys@gmail.com
  rubygems_user: kenhys
  slideshare_user: kenhys
  speaker_deck_user: 
